# k-Nearest Neighbors 

# Similarity and Distance Measures

In [19]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

sentence1 = "This is the first sentence in English."
sentence2 = "Another sentence also in English."
sentence3 = "This is not a sentence."

documents = [sentence1 , sentence2 , sentence3]
cV = CountVectorizer() # count how often each word appears

doc_term_matrix = cV.fit_transform(documents).todense()

In [20]:
doc_term_matrix

matrix([[0, 0, 1, 1, 1, 1, 0, 1, 1, 1],
        [1, 1, 1, 0, 1, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 1, 1, 1, 0, 1]], dtype=int64)

In [21]:
from sklearn.metrics.pairwise import cosine_similarity

# convert matrix to numpy
doc_term_matrix = np.asarray(doc_term_matrix)

cosine_similarity(doc_term_matrix)

array([[1.        , 0.50709255, 0.56694671],
       [0.50709255, 1.        , 0.2236068 ],
       [0.56694671, 0.2236068 , 1.        ]])

In [22]:
from sklearn.metrics import pairwise_distances
for m in ['manhattan','euclidean']:
    print(m)
    print(pairwise_distances(doc_term_matrix, metric=m))

manhattan
[[0. 6. 5.]
 [6. 0. 7.]
 [5. 7. 0.]]
euclidean
[[0.         2.44948974 2.23606798]
 [2.44948974 0.         2.64575131]
 [2.23606798 2.64575131 0.        ]]


# kNN for Iris Flowers

In [23]:
from sklearn import neighbors, datasets
from sklearn.metrics import accuracy_score
    
n_neighbors = 15

# import some data to play with
iris = datasets.load_iris()

# we only take the first two features to make it more challenging 
X = iris.data[:, :2]
y = iris.target

# Standard-scalar of the features
# (in this case, maybe not really necessary)
from sklearn.preprocessing import StandardScaler
# X = StandardScaler().fit_transform(X)

# create an instance of Neighbor Classifier and fit the data
clf = neighbors.KNeighborsClassifier(n_neighbors, weights='uniform')
clf.fit(X, y)
accuracy_score(y, clf.predict(X))

0.8133333333333334

In [24]:
# --->>> Your Turn <<<---
# Experiment with different settings for the parameters:
#  - n_neighbors
#  - weights 
#  - algorithm
#  - leaf_size
# (see: https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html)
# What do you observe?

In [ ]:
# --->>> Your Turn <<<---
# Use radius-neighbors instead of k-nearest-neighbors

In [ ]:
# --->>> Your Turn <<<---
# What do you think about the generalsiation ability of the k-nearest-neighbors algorithm?