In [2]:
import numpy as np

In [3]:
# create an array
a = np.array([2, 3, 4]) 
a

array([2, 3, 4])

In [4]:
# initialize an array with a range of values 
# and reshape it into a matrix
a = np.arange(15).reshape(3, 5) 
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a.shape

(3, 5)

In [6]:
a.ndim

2

In [7]:
# calculate the element-wise product of two matrices
A = np.array([[1, 1],[0, 1]])
B = np.array([[2, 0],[3, 4]])
A * B 

array([[2, 0],
       [0, 4]])

In [8]:
# calculate the matrix product
A @ B 

array([[5, 4],
       [3, 4]])

In [9]:
# a new matrix
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
# sum of each column
b.sum(axis=0) 

array([12, 15, 18, 21])

In [11]:
# min of each row
b.min(axis=1)

array([0, 4, 8])

In [12]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [13]:
# access array elements
a[2]

8

In [14]:
a[2:5]

array([ 8, 27, 64])

In [15]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
b[2, 3]

11

In [17]:
# each row in the second column of b
b[0:5, 1]

array([1, 5, 9])

In [18]:
# equivalent to the previous example
b[:, 1]

array([1, 5, 9])

In [19]:
# last row of b
# equivalent to b[-1, :]
b[-1] 

array([ 8,  9, 10, 11])

In [20]:
a = np.arange(12)**2          # the first 12 square numbers
i = np.array([1, 1, 3, 8, 5]) # an array of indices
a[i] # the elements of ‘a‘ at the positions ‘i‘

array([ 1,  1,  9, 64, 25])